spring:
  application:
    name: physical-security-dashboard
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
