spring:
  security:
    user:
      name: ${APP_USERNAME:admin}
      password: ${APP_PASSWORD:dev-password}
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:physical_security_dashboard}
    username: ${POSTGRES_USER:myuser}
    password: ${POSTGRES_PASSWORD:secret}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
