spring:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:physical_security_dashboard}
    username: ${POSTGRES_USER:myuser}
    password: ${POSTGRES_PASSWORD:secret}
